apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: food-ordering-system
type: Opaque
data:
  # The values below are base64 encoded versions of your .env file values
  # You can encode them with: echo -n "your-value" | base64
  ORDER_SERVICE_MONGO_URI: bW9uZ29kYitzcnY6Ly9yZDkyNzpyZDkyN0BEUy50Y25tZ3V1Lm1vbmdvZGIubmV0L0RTP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  PAYMENT_SERVICE_MONGO_URI: bW9uZ29kYitzcnY6Ly9BRl9Qcm9qZWN0OmVJQmh5a1A1YVpwN2ZsV3JAcGF5bWVudC55ZGVoMy5tb25nb2RiLm5ldC9EU19Qcm9qZWN0
  RESTAURANT_SERVICE_MONGO_URI: bW9uZ29kYitzcnY6Ly9pdDIyMTcyNjAwOnZhcmFuYW5AY2x1c3RlcjAuY2FtZGgubW9uZ29kYi5uZXQvcmVzdGF1cmFudC1zZXJ2aWNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  USER_SERVICE_MONGO_URI: bW9uZ29kYitzcnY6Ly9yZDkyNzpyZDkyN0BBRnRlc3QudGNubWd1dS5tb25nb2RiLm5ldC9BRnRlc3Q/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  DELIVERY_SERVICE_MONGO_URI: bW9uZ29kYitzcnY6Ly9yZDkyNzpyZDkyN0BEU0RlbGl2ZXJ5LnRjbm1ndXUubW9uZ29kYi5uZXQvRFNEZWxpdmVyeT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  RESTAURANT_SERVICE_JWT_SECRET: PHlvdXIgand0IHNlY3JldD4=
  USER_SERVICE_JWT_SECRET: OGxEckh3OFl0ek5ialJDR2JCU09EOVh5cW1sOWl2NnVqSzNmRHd0QVR1az0=