apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-uploads-pvc
  namespace: food-ordering-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi