apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: food-ordering-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: rdarshan927/food-ordering-system-delivery-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DELIVERY_SERVICE_MONGO_URI
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: RABBITMQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: RABBITMQ_PORT
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        resources:
          limits:
            cpu: "500m"
            memory: "768Mi"
          requests:
            cpu: "200m"
            memory: "512Mi"