apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food-ordering-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rdarshan927/food-ordering-system-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://order-service:5051"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"