apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: food-ordering-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: rdarshan927/food-ordering-system-notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: NODE_ENV
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: RABBITMQ_URL
        resources:
          limits:
            cpu: "200m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"