apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: food-ordering-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: rdarshan927/food-ordering-system-restaurant-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: RESTAURANT_SERVICE_MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: RESTAURANT_SERVICE_JWT_SECRET
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: restaurant-uploads-pvc