apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: food-ordering-system
spec:
  selector:
    app: delivery-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP