apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: food-ordering-system
spec:
  selector:
    app: notification-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP