apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: food-ordering-system
spec:
  selector:
    app: order-service
  ports:
    - port: 5051
      targetPort: 5051
  type: ClusterIP