apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
  namespace: food-ordering-system
spec:
  selector:
    app: usermanagement-service
  ports:
    - port: 5052
      targetPort: 5052
  type: ClusterIP